### ISSUE TITLE
Footer Turns Into A Link

### ISSUE THREAD

**Issue by Yugen-X** [Yugen-X/JWD_Remix#4]
**Card is misaligned**
-The bottom left-most card isn't sized correctly and needs to match the card above it 

**Links Not Working Properly **
-When links are added to the cards the footer turns into a link itself for one of the cards

solutions tried 
- Removed the link (it just goes to the next link before the one that is removed)
- removed the footer(Links still show at the bottom of the page they should display on the picture of the food)

**Comment by Halim-Shams** [comment]
Hey friend,

I just wanted to solve your problem, but I didn't get your point. If you can, please make it a bit obvious that really where is the problem.

Thanks!

**Comment by Yugen-X** [comment]
Hello Halim,

There was an issue at the bottom of the webpage where the footer is I believe in the previous version I commented out the footer, but essentially the entire footer of my website would turn into a link and I now know why, it was really late when I was working on this so I overlooked some pretty simple stuff, I did not close the <a> tags and because of that it was resulting in the entire footer turning into one big link. Thanks for trying to help.

Thank you, 
Yugen
